travis:
  secure:
    BINSTAR_TOKEN: gicIAefG5xhDnuAT3P2ATHekie6NL1cwCsLERhzpk+RT6E+BcQ22bQaPKWcg5m8muIW27PlyhqKSPlvkF1GkUyRUxva/xluWwAfMipx03HBgAS732mJPfTqQX3GF5P/8KrF61oIb6Rkal/jWpciApl365kf64LBOAWgum1iSDay56Ng2+M09C3l5M2PiBUAGTpS9+SEV8MNWmIctbywTgQBZhyxPicOMlw/T4SLjbDbXDyOgK4wEuNkczV9BDga3mheurKc89ouqvw9Xgfx0reoSvrBPeE1NeoPN1CrVoSpGVboPP4U+ilwtYhCr9W5BPwHrp/bP24GUdYexWqHEbG6rB8EBt7pZj2eaH/izOg5XCTGPMe3b0AHZsbNoVQlNoy+xfcB9DLghNROZnOGVL4487al6zocbMw9xYDviyyKZlFuyKbrmQanXThqprCny16fAlfIDkTyu2773YRqaVFnIrpw+Bm5vquw6jGaUIcsTSpIAk8cFN/3/H1JzUUtpcCslD7ioLX7VqtAgJUlCjNc8OntPizRaf0BsZ36GjyyYUJjhBNQU7vQfXk/sDhdYOdRVqvuSLe4v76v+t3UOBGJR2XeK5LWmmLpPek94t35yc1c7ilAFqRbd34v79jU3YT+BITXlsPsiIICI5bEywTDdf5OtFe4AFKy7BgdtjEo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
